README.md, preview/Dockerfile, preview/README.md
=> Add Dockerfile and update README

preview/Dockerfile
=> Temporarily work around LTTng assert

preview/Dockerfile
=> Updating Dockerfile with CLI shared framework installer changes

preview/Dockerfile
Fixes #20 
@naamunds, @dleeapho
=> Triggered the building of local package cache

rel-1.0.0/README.md, rel-1.0.0/debian/Dockerfile, rel-1.0.0/debian/core-deps/Dockerfile, rel-1.0.0/debian/core-deps/hooks/post_build, rel-1.0.0/debian/core-deps/hooks/post_push, rel-1.0.0/debian/core/Dockerfile, rel-1.0.0/debian/hooks/post_build, rel-1.0.0/debian/hooks/post_push, rel-1.0.0/debian/onbuild/Dockerfile, rel-1.0.0/nanoserver/Dockerfile, rel-1.0.0/nanoserver/core/Dockerfile, rel-1.0.0/nanoserver/onbuild/Dockerfile, rel-1.0.0/windowsservercore/Dockerfile, rel-1.0.0/windowsservercore/core/Dockerfile, rel-1.0.0/windowsservercore/onbuild/Dockerfile
=> Add new image types to match official repo

ISSUE_TEMPLATE
=> Added an ISSUE_TEMPLATE

rel-1.0.0/nanoserver/Dockerfile, rel-1.0.0/nanoserver/core/Dockerfile, rel-1.0.0/windowsservercore/Dockerfile, rel-1.0.0/windowsservercore/core/Dockerfile
=> Updated Windows images to be based on specific OS image from Docker Hub

rel-1.0.0/debian/Dockerfile
=> Removed workaround for https://github.com/docker/docker/issues/20818

rel-1.0.0/README.md
=> Fix Dockerfile links and paths in README

netci.groovy
=> Fix typo in netci.groovy

rel-1.0.0/debian/Dockerfile, rel-1.0.0/debian/core/Dockerfile, rel-1.0.0/nanoserver/Dockerfile, rel-1.0.0/nanoserver/core/Dockerfile, rel-1.0.0/windowsservercore/Dockerfile, rel-1.0.0/windowsservercore/core/Dockerfile
=> Update to .NET 1.0.1 and SDK 1.0.0-preview3-003585

rel-1.0.0/nanoserver/Dockerfile, rel-1.0.0/nanoserver/core/Dockerfile
=> Fix for forwarders workaround on 1.0.1

netci.groovy
=> Enable CI on Nano Server

rel-1.0.0/README.md
=> Fix broken README links

build-and-test.ps1, build-and-test.sh, test/run-test.ps1, test/run-test.sh
=> Make test scripts match official repo

rel-1.0.0/nanoserver/Dockerfile, rel-1.0.0/nanoserver/core/Dockerfile
=> Modified Nano Dockerfiles to make use of new Invoke-WebRequest support

rel-1.0.0/README.md, rel-1.0.0/debian/Dockerfile, rel-1.0.0/nanoserver/Dockerfile, rel-1.0.0/windowsservercore/Dockerfile, test/run-test.ps1
Ported https://github.com/dotnet/dotnet-docker/pull/124 to the nightly repo.
cc @naamunds
=> Cleanup trailing whitespace

rel-1.0.0/debian/core-deps/Dockerfile, rel-1.0.0/debian/core/Dockerfile
See https://github.com/dotnet/dotnet-docker/issues/121.
cc: @MichaelSimons @glennc
=> Add ca-certificates to core-deps

rel-1.0.0/nanoserver/Dockerfile, rel-1.0.0/nanoserver/core/Dockerfile
=> Updated NanoServer Dockerfiles to 10.0.14393.321

rel-1.0.0/README.md
/cc @MichaelSimons @richlander
=> Make README consistent with official repo

rel-1.0.0-preview2.1/debian/Dockerfile, rel-1.0.0-preview2.1/debian/core-deps/Dockerfile, rel-1.0.0-preview2.1/debian/core-deps/hooks/post_build, rel-1.0.0-preview2.1/debian/core-deps/hooks/post_push, rel-1.0.0-preview2.1/debian/core/Dockerfile, rel-1.0.0-preview2.1/debian/hooks/post_build, rel-1.0.0-preview2.1/debian/hooks/post_push, rel-1.0.0-preview2.1/debian/onbuild/Dockerfile, rel-1.0.0-preview2.1/nanoserver/Dockerfile, rel-1.0.0-preview2.1/nanoserver/core/Dockerfile, rel-1.0.0-preview2.1/nanoserver/onbuild/Dockerfile, rel-1.0.0/README.md, test/NuGet.Config, test/create-run-publish-app.sh, test/run-test.sh, update-dependencies/Config.cs, update-dependencies/Program.cs
=> Added Dockerfiles for rel-1.0.0-preview2.1 branch of CLI

netci.groovy
=> Enable CI on Windows

rel-1.0.0/debian/sdk/Dockerfile, test/create-run-publish-app.sh
This build contains the csproj changes but requires the usage of the "3" verbs.  Updated CI tests accordingly.
@naamunds.
=> Update rel-1.0.0 SDK Dockerfile to build 1.0.0-preview3-003892

rel-1.0.0-preview2.1/debian/runtime/Dockerfile, rel-1.0.0-preview2.1/debian/sdk/Dockerfile, rel-1.0.0-preview2.1/nanoserver/runtime/Dockerfile, rel-1.0.0-preview2.1/nanoserver/sdk/Dockerfile
=> Update rel-1.0.0-preview2.1 SDK to preview2-1-003167

rel-1.0.0/README.md
=> Added plain sdk tags

rel-1.0.0/debian/sdk/Dockerfile
=> Update Debian sdk Dockerfile to CLI 1.0.0-preview3-003933

update-dependencies/Config.cs, update-dependencies/Program.cs
This requires an update to the Maestro subscriptions as well.
@naamunds
=> Updated update-dependencies to work with latest Dockerfile refactoring

1.0/debian/sdk/msbuild/Dockerfile, 1.1/debian/sdk/msbuild/Dockerfile
=> Update Debian sdk Dockerfiles to CLI 1.0.0-preview3-004050

1.1/README.md
=> Fixed incorrect tag listed for 1.0.1-sdk-projectjson-nanoserver

1.0/nanoserver/runtime/Dockerfile, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.0/nanoserver/sdk/projectjson/Dockerfile, 1.1/nanoserver/runtime/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/projectjson/Dockerfile
=> Updating Nano Server Dockerfiles to be based on 10.0.14393.447

1.0/debian/sdk/msbuild/Dockerfile, 1.1/debian/sdk/msbuild/Dockerfile
=> Update msbuild sdk Dockerfiles to 1.0.0-preview3-004056

1.1/debian/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile, test/NuGet.Config, test/create-run-publish-app.ps1, test/create-run-publish-app.sh
=> Add logic to cache 1.1 packages for 1.1-sdk-msbuild image

1.0/README.md, 1.0/nanoserver/sdk/projectjson/Dockerfile, README.md
=> Misc edits to sync artifacts with official

1.0/README.md
Related to https://github.com/dotnet/dotnet-docker/issues/161
@naamunds
=> Changed single quotes to back-ticks in tags section for better formatting/readability

1.0/README.md, 1.0/debian/runtime-deps/hooks/post_push, 1.0/debian/runtime/Dockerfile, 1.0/debian/sdk/msbuild/Dockerfile, 1.0/debian/sdk/projectjson/Dockerfile, 1.0/nanoserver/runtime/Dockerfile, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.0/nanoserver/sdk/projectjson/Dockerfile, test/create-run-publish-app.ps1, test/create-run-publish-app.sh
=> Introduce 1.0.3 artifacts

1.0/debian/runtime-deps/hooks/post_push, 1.0/debian/sdk/msbuild/hooks/post_push, 1.0/debian/sdk/projectjson/hooks/post_push, 1.1/debian/runtime-deps/hooks/post_push, 1.1/debian/sdk/msbuild/hooks/post_push, 1.1/debian/sdk/projectjson/hooks/post_push
=> Add builds hooks to produce sdk multi-tags

1.0/README.md, 1.1/debian/runtime-deps/hooks/post_push, 1.1/debian/sdk/msbuild/hooks/post_push, 1.1/debian/sdk/projectjson/hooks/post_push
=> Added missing 1-sdk-* tags

1.0/nanoserver/runtime/Dockerfile, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.0/nanoserver/sdk/projectjson/Dockerfile, 1.1/nanoserver/runtime/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/projectjson/Dockerfile
@dotnet-bot test NanoServer please
=> Updating Nano Server Dockerfiles to be based on 10.0.14393.576

1.0/README.md, 1.0/debian/runtime-deps/hooks/post_push, 1.0/debian/sdk/msbuild/Dockerfile, 1.0/debian/sdk/msbuild/hooks/post_push, 1.0/debian/sdk/projectjson/hooks/post_push, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.1/debian/runtime-deps/hooks/post_push, 1.1/debian/sdk/msbuild/Dockerfile, 1.1/debian/sdk/msbuild/hooks/post_push, 1.1/debian/sdk/projectjson/hooks/post_push, test/create-run-publish-app.sh
=> Integrated CLI preview5 and rev'd versions

1.0/nanoserver/runtime/Dockerfile, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.0/nanoserver/sdk/projectjson/Dockerfile, 1.1/nanoserver/runtime/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/projectjson/Dockerfile
https://github.com/dotnet/dotnet-docker-samples/pull/24
=> Updating Nano Server Dockerfiles to be based on 10.0.14393.693

1.0/debian/sdk/msbuild/Dockerfile, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.1/debian/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile
I will also be updating the Maestro handled accordingly to gen PRs when new RC3 builds are available.
=> Update to CLI 1.0.0-rc3-004488

1.0/debian/sdk/msbuild/Dockerfile, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.1/debian/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile
Updating manually since CLI is not updating their [versions file](https://github.com/dotnet/versions/tree/master/build-info/dotnet/cli/rel/1.0.0-rc3) therefore Maestro is not doing this.
=> Update CLI to 1.0.0-rc3-004500

1.0/README.md, 1.0/debian/sdk/msbuild/Dockerfile, 1.0/debian/sdk/msbuild/hooks/post_push, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.1/debian/sdk/msbuild/Dockerfile, 1.1/debian/sdk/msbuild/hooks/post_push, 1.1/nanoserver/sdk/msbuild/Dockerfile
=> Upgrade to RC4 CLI

1.0/nanoserver/runtime/Dockerfile, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.0/nanoserver/sdk/projectjson/Dockerfile, 1.1/nanoserver/runtime/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/projectjson/Dockerfile
This PR ports the following changes from official - https://github.com/dotnet/dotnet-docker/commit/a21b5fd144bb9f3fcf41075fca1ffa47e3d4afac.
=> Porting Windows Dockerfile changes from official

1.0/README.md
related to https://github.com/dotnet/dotnet-docker/issues/186
=> Removed the number of Docker pulls and stars from the readme

1.0/README.md
Changed `dotnet new` Console initiation to `dotnet new console`
Changed `dotnet new -t web` ASP.NET Core initiation to `dotnet new mvc`
=> Fix dotnet new cmds

1.0/debian/sdk/Dockerfile, 1.0/nanoserver/sdk/Dockerfile, 1.1/debian/sdk/Dockerfile, 1.1/nanoserver/sdk/Dockerfile, test/Dockerfile.linux.publish, test/run-test.ps1
Along with this version change, a small test change was needed to get the pre-release packages from MyGet since they are not available on NuGet.
=> Update rel-1.0.0 SDK to rc4-004893

test/run-test.ps1
FYI - GitHub is making the diff look worse than it is because of the whitespace changes.
=> Added logic to run-test script to cleanup test images

update-dependencies/update-dependencies.csproj, update-dependencies/update-dependencies.ps1
=> Updating update-dependencies to use CLI 1.0.1

README.md
Related to #228
The preview sample was removed with dotnet/dotnet-docker-samples#27.
=> Removed old preview sample link

2.0/debian/runtime/Dockerfile, 2.0/debian/sdk/Dockerfile, 2.0/nanoserver/runtime/Dockerfile, 2.0/nanoserver/sdk/Dockerfile
Updating 2.0.0 to cli's preview1 channel instead of master.
fixes #281
=> Update release-2.0.0 SDK to 2.0.0-preview1-005909

build-pipeline/dotnet-docker-nightly-windows-images.json
=> fix broken reference to image builder tool in windows build def

2.0/sdk/jessie/Dockerfile, 2.0/sdk/nanoserver/Dockerfile, update-dependencies/CliDependencyHelper.cs
Respond to CLI installer rename - https://github.com/dotnet/cli/pull/6714
=> Updates per CLI installer rename

2.0/runtime/jessie/Dockerfile, 2.0/runtime/nanoserver/Dockerfile, 2.0/sdk/jessie/Dockerfile, 2.0/sdk/nanoserver/Dockerfile, update-dependencies/Config.cs, update-dependencies/DockerfileShaUpdater.cs, update-dependencies/Program.cs
Related to https://github.com/dotnet/dotnet-docker/issues/43
=> Update 2.0 Dockerfiles to include checksum verification

1.0/runtime/nanoserver/Dockerfile, 1.0/sdk/nanoserver/Dockerfile, 1.1/runtime/nanoserver/Dockerfile, 1.1/sdk/nanoserver/Dockerfile, 2.0/runtime/nanoserver/Dockerfile, 2.0/sdk/nanoserver/Dockerfile, manifest.json
Updating Nano Server Dockerfiles to be based on 10.0.14393.1358
=> Updating Nano Server Dockerfiles to be based on 10.0.14393.1358

README.md, manifest.json
=> Change 2.0 multi-arch tags to be based on stretch

2.0/runtime/jessie/Dockerfile, 2.0/runtime/stretch/Dockerfile
=> Fix broken *-runtime-jessie tags so that they are based on jessie

build-pipeline/dotnet-docker-linux-images.json, build-pipeline/dotnet-docker-post-image-build.json, build-pipeline/dotnet-docker-windows-images.json
related to https://github.com/dotnet/docker-tools/issues/13
=> Update image-builder to latest version

build-pipeline/dotnet-docker-linux-images.json, build-pipeline/dotnet-docker-post-image-build.json, build-pipeline/dotnet-docker-windows-images.json
Related to https://github.com/dotnet/dotnet-docker/issues/257 and https://github.com/dotnet/dotnet-docker/issues/256
=> Update Agent pool and tweak cleanup step settings

.gitignore, update-dependencies/CliDependencyHelper.cs, update-dependencies/Program.cs
=> Fixed path issue and misc cleanup in update-dependencies

README.md, manifest.json
=> Updates for 2.0.0-preview3 tagging

build-and-test.ps1, build-pipeline/dotnet-docker-linux-images.json, build-pipeline/dotnet-docker-post-image-build.json, build-pipeline/dotnet-docker-windows-images.json, build-pipeline/pipeline.json, manifest.json, test/run-test.ps1
In the test build I ran the longest windows build leg took 12.9 minutes whereas the single Linux build leg took 14.6 minutes.
=> Break apart builds into multiple legs to reduce time

netci.groovy
Related https://github.com/dotnet/dotnet-docker/issues/264
=> Broke apart CI into more jobs

test/run-test.ps1
Related dotnet/dotnet-docker#270
=> Remove test workaround for self-contained apps

README.md, manifest.json
=> Move latest tags to 2.0 images

build-pipeline/dotnet-docker-linux-amd64-images.json, build-pipeline/dotnet-docker-linux-arm32v7-images.json, build-pipeline/dotnet-docker-windows-amd64-images.json
Change needed with latest image-builder.
=> Fixup test-var options in builds

build-pipeline/dotnet-docker-linux-amd64-images.json, build-pipeline/dotnet-docker-linux-arm32v7-images.json, build-pipeline/dotnet-docker-post-image-build.json, build-pipeline/dotnet-docker-windows-amd64-images.json
=> Upgrading image builder to latest

build-pipeline/dotnet-docker-linux-amd64-images.json, build-pipeline/dotnet-docker-linux-arm32v7-images.json, build-pipeline/dotnet-docker-post-image-build.json, build-pipeline/dotnet-docker-windows-amd64-images.json
@dotnet/dotnet-cli skip CI please
=> Upgrade image builder to latest

1.0/sdk/jessie/Dockerfile, 1.0/sdk/nanoserver/Dockerfile, 1.1/sdk/jessie/Dockerfile, 1.1/sdk/nanoserver/Dockerfile, manifest.json, update-dependencies/CliDependencyHelper.cs, update-dependencies/Program.cs, update-dependencies/update-dependencies.csproj, update-dependencies/update-dependencies.ps1
Related #364 
Note:  Latest SDK hasn't picked up the latest runtime versions yet therefore the runtime images won't be updated at this time.
=> Update to sdk 1.1.0

2.1/runtime-deps/jessie/amd64/Dockerfile, 2.1/runtime-deps/stretch/amd64/Dockerfile, 2.1/runtime-deps/stretch/arm32v7/Dockerfile, 2.1/runtime/jessie/amd64/Dockerfile, 2.1/runtime/nanoserver/amd64/Dockerfile, 2.1/runtime/stretch/amd64/Dockerfile, 2.1/runtime/stretch/arm32v7/Dockerfile, 2.1/sdk/jessie/amd64/Dockerfile, 2.1/sdk/nanoserver/amd64/Dockerfile, 2.1/sdk/stretch/amd64/Dockerfile, README.md, build-pipeline/pipeline.json, manifest.json, netci.groovy, test/run-test.ps1
=> Add 2.1 Dockerfiles

build-pipeline/dotnet-docker-linux-amd64-images.json, build-pipeline/dotnet-docker-linux-arm32v7-images.json, build-pipeline/dotnet-docker-post-image-build.json, build-pipeline/dotnet-docker-windows-amd64-images.json
=> Upgrade to the latest image-builder

manifest.json
Related to #407 
@dotnet-bot skip CI please.
=> Updating nanoserver-insider tags to latest

build-pipeline/dotnet-docker-linux-arm32v7-images.json
=> Update arm build demands to not be tied to a specific machine

build-pipeline/dotnet-docker-linux-arm32v7-images.json
Moved arm build legs to a new core engineering infra dedicated build pool.
=> Changed build pool to use new infra pool instead of test pool

build-and-test.ps1
Display Docker version information where the build and tests are being performed.
=> Display Docker version information.

build-pipeline/dotnet-docker-linux-arm32v7-images.json
Refer https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1020801&_a=summary
=> Disable ARM tests in official builds.

README.md
Porting https://github.com/dotnet/dotnet-docker/pull/299 and https://github.com/dotnet/dotnet-docker/pull/282 into nightly.
@dotnet-bot skip ci please.
=> Porting readme changes from official repo into nightly

test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
=> Update tests to use correct sdk tag

build-pipeline/dotnet-docker-linux-arm32v7-images.json
Disable ARM test. Also includes -
- Disable building of SDK images build task.
- Reset `jobTimeoutInMinutes` to 60.
=> Disable ARM tests.

manifest.json, scripts/Get-Tags.ps1, scripts/Get-TagsDocumentation.ps1
Removes Nano Version from non-fully qualified tags. 
Refer https://github.com/dotnet/dotnet-docker/issues/312
=> Stop producing Nano Server Version suffixed tags.

README.md, manifest.json
Fixes dotnet/dotnet-docker#323
=> Add <major>-<minor> non-manifest tags

manifest.json, scripts/Get-TagsDocumentation.ps1
Rollout of dotnet/docker-tools#56
=> Update Get-TagsDocumentation.ps1 for RS3 images

README.md
Related to dotnet/dotnet-docker#340
=> Add note about req Docker version

scripts/Get-TagsDocumentation.ps1
Related to dotnet/docker-tools#58
=> Update Get-TagsDocumentation.ps1 to update readme

2.1/runtime/alpine/amd64/Dockerfile, 2.1/runtime/jessie/amd64/Dockerfile, 2.1/runtime/nanoserver-1709/amd64/Dockerfile, 2.1/runtime/nanoserver-sac2016/amd64/Dockerfile, 2.1/runtime/stretch/amd64/Dockerfile, 2.1/runtime/stretch/arm32v7/Dockerfile, 2.1/sdk/jessie/amd64/Dockerfile, 2.1/sdk/nanoserver-1709/amd64/Dockerfile, 2.1/sdk/nanoserver-sac2016/amd64/Dockerfile, 2.1/sdk/stretch/amd64/Dockerfile, update-dependencies/DockerfileShaUpdater.cs
=> Remove download url and sha ENV instructions in 2.1 Dockerfiles

update-dependencies/CliDependencyHelper.cs, update-dependencies/DockerfileShaUpdater.cs
=> Refactor UpdateDependencies in response to cli repo updates

build-and-test.ps1, netci.groovy
Refer to https://github.com/dotnet/dotnet-docker-nightly/issues/529
=> Provide option to cleanup Docker assets

build-and-test.ps1
Refer to https://github.com/dotnet/dotnet-docker-nightly/issues/529
This fixes the regression introduced through 9661873.  `docker system prune -a -f` will be used in non-Windows path to cleanup Docker assets.
=> Cleanup Docker assets during CI

manifest.json, netci.groovy, test/Dockerfile.linux.testrunner
=> Refactor Docker.linux.testrunner to use prebuilt image with Docker and PowerShell

build-pipeline/dotnet-docker-linux-arm32v7-images.json
=> Disable intermittent failing arm tests
