preview/Dockerfile
This reduces the image size by ~21mb.  This resolves #5.
@naamunds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dotnet/dotnet-docker-preview/6)
=> Added logic to cleanup the apt cache.

preview/Dockerfile
All of our Docker images will be Debian based for RC2 (https://github.com/dotnet/dotnet-docker/issues/11).  CLI now supports Debian therefore the preview image was updated accordingly.  Keep in mind the CLI Debian installer work is out of scope for RC2 therefore the Dockerfile needs to contain the logic to install CLI.
/cc @naamunds, @dleeapho
=> Update Dockerfile to be Debian based

preview/Dockerfile
This is needed in order to get the latest preview2 bits.  The beta channel is not going to be used going forward.
fixes #15
@dleeapho, @naamunds
=> Updated Dockerfile to pull .NET CLI from the preview channel

preview/Dockerfile
=> Removed the clang-3.5 and liblldb-3.6 packages from the image

.gitignore, update-dependencies/Config.cs, update-dependencies/NuGet.config, update-dependencies/Program.cs, update-dependencies/project.json, update-dependencies/update-dependencies.ps1, update-dependencies/update-dependencies.xproj
The update-dependencies .NET app must be invoked from the root of the
repo.  A update-dependencies.ps1 script is also provided which installs
the .NET CLI and then compiles and invokes the app; this script can be
invoked from anywhere.
The plan is for Maestro to invoke a VSTS build definition whenever a new
CLI build is available, which will invoke the update-dependencies.ps1
script.
Also add a .gitignore file.
cc: @MichaelSimons
=> Add app to automatically update dependency versions

update-dependencies/Program.cs, update-dependencies/project.json
The regex pattern for the DOTNET_SDK_VERSION was including \r in its
matches, causing the \r to be removed from that line when the version
string was replaced. This is because by default the '.' language element
matches every character except \n. The fix is to explicitly match every
character except \r and \n so that the pattern matches don't include \r.
This change also adds a Trace Listener so that useful output from
VersionTools is captured in the output of the app.
cc: @MichaelSimons @dagood
=> Fix regex to handle CRLF line endings

.gitignore, build-and-test.sh, netci.groovy, test/create-run-publish-app.sh, test/run-test.sh
Whenever a PR is created in the dev or master branch, a Jenkins job will
build each Debian Dockerfile and run tests.  The tests perform a simple
smoke test on the images.
In this initial implementation, only the Debian images are built and
tested.  The plan is to eventually test the Windows Server images also.
/cc: @MichaelSimons @mmitche
=> Add Jenkins CI and automated tests for Debian

netci.groovy
Disabling CI on Windows for the time being given issues with getting machines configured correctly to run CI on.
cc @naamunds
=> Disable CI on Windows

rel-1.0.0/nanoserver/Dockerfile, rel-1.0.0/nanoserver/core/Dockerfile, rel-1.0.0/windowsservercore/Dockerfile, rel-1.0.0/windowsservercore/core/Dockerfile
With this version the forwarders workaround is no longer needed.
cc @naamunds
=> Updated Windows Dockerfiles to build 10.0.14393.206

test/create-run-publish-app.sh, test/run-test.sh
Test core-deps by creating a self-contained app in the sdk container,
and then running the self-contained app's published executable in a
core-deps container.
Also fix running with DEBUGTEST by putting the trailing space in
"optional_docker_run_args" instead of in the "docker run" commands to
eliminate the two consecutive spaces.
This PR is porting https://github.com/dotnet/dotnet-docker/pull/118 to this repo.
cc: @MichaelSimons
=> Add CI for core-deps images

update-dependencies/Config.cs, update-dependencies/Program.cs
Currently the update-dependencies implementation only handles changes from a single CLI branch correctly.  If Maestro is hooked up to multiple branches and builds happen for those branches concurrently, update-dependencies will create a single PR to update the Dockerfiles corresponding to the multiple branches.  This is not the desired behavior, we need the ability to merge in changes from branches independently.  For example, right now we don't want to merge in changes from rel/1.0.0 because it is in a bad state but we want the changes coming from rel/1.0.0-preview2.1. 
@naamunds, @dagood
=> Modified update-dependencies to handle PRs from multiple CLI branches

1.0/debian/runtime-deps/hooks/post_push, 1.0/debian/runtime/Dockerfile, 1.0/debian/sdk/msbuild/Dockerfile, 1.0/debian/sdk/projectjson/Dockerfile, 1.0/nanoserver/runtime/Dockerfile, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.0/nanoserver/sdk/projectjson/Dockerfile, 1.1/README.md, test/create-run-publish-app.ps1, test/create-run-publish-app.sh
Using 1.0.2 was a mistake.  1.0.2 didn't ship any updates for Debian.  1.0.1 is the current runtime the Dockerfiles should be using.
=> Updated 1.0 Dockerfiles to use 1.0.1

1.1/README.md
I copied the readme from the official repo verbatim and changed the microsoft/dotnet references to microsoft/dotnet-nightly.  There is one section that is technically incorrect. 
```
You can run a sample application (Linux image) that depends on these images in a container by running the following command.
docker run microsoft/dotnet-samples
```
The reason I didn't change this is because I didn't want diverging readme's between the two repos to be a high maintenance task.  @richlander - please provide feedback your thoughts on this.  
Fixes #84
=> Update readme to align with official readme

1.0/README.md, 1.0/debian/runtime-deps/hooks/post_push, 1.1/debian/runtime-deps/hooks/post_push, 1.1/debian/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile, test/create-run-publish-app.ps1, test/create-run-publish-app.sh
These changes include the build hooks to create the deprecated "core" tags.  This is done to make the release process easier in that nightly is truly a staging environment for official.   
@naamunds
=> Back porting official changes to nightly

update-dependencies/Program.cs
I discovered this issue while adding a Maestro hook to update preview2.  It was also replacing the preview2-1 version which is incorrect.
@naamunds
=> Modified update-dependencies logic to handle distinguishing preview2 from preview2-1

build-and-test.ps1, netci.groovy, test/create-run-publish-app.ps1, test/run-test.ps1
This is the first iteration towards having one set of CI scripts for all supported platforms.  The next step would be to get Jenkins to install Powershell and utilize these changes.  Once this is done the bash scripts can be removed and we then only have one set of scripts to maintain.
@naamunds
=> Modified build-and-test.ps1 to be xplat

1.0/debian/sdk/msbuild/Dockerfile, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.1/debian/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile, test/create-run-publish-app.ps1, test/create-run-publish-app.sh
CLI is now based on 1.0.3 therefore we no longer need to explicitly install the 1.0.3 runtime for the 1.0 images.  Additionally the latest CLI now supports Nano Server again therefore the nano images were updated to use the latest preview5 CLI.
=> Upgrading to CLI 1.0.0-preview5-004432

1.1/debian/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile
This is no longer necessary because of https://github.com/dotnet/cli/pull/5225
=> Removed explicit install of 1.1 runtime in 1.1-sdk-msbuild Dockerfiles

1.1/debian/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile, test/create-run-publish-app.ps1, test/create-run-publish-app.sh
With the latest changes CLI made to install both the current and LTS runtime, the warmup logic was also modified to initialize the NuGet package cache for both.  Because of this, the logic needed to trigger the cache warmup for current is not needed therefore it was removed.  I also tweaked the test code to make use of the new -t console1.1 logic for simplification.
=> Utilize dotnet package warmup logic for rc3

1.0/debian/sdk/msbuild/Dockerfile, 1.0/nanoserver/sdk/msbuild/Dockerfile, 1.1/debian/sdk/msbuild/Dockerfile, 1.1/nanoserver/sdk/msbuild/Dockerfile, test/run-test.ps1
The latest CLI introduced [new `dotnet new` functionality](2d93968a88a724ec69a3c3cfd0ad92576101cbfe) therefore the tests needed to be updated accordingly.
=> Updating to CLI to 1.0.0-rc4-004756

1.0/README.md, 2.0/debian/runtime-deps/Dockerfile, 2.0/debian/runtime-deps/hooks/post_build, 2.0/debian/runtime-deps/hooks/post_push, 2.0/debian/runtime/Dockerfile, 2.0/debian/sdk/Dockerfile, 2.0/debian/sdk/hooks/post_push, 2.0/nanoserver/runtime/Dockerfile, 2.0/nanoserver/sdk/Dockerfile
projectjson support was dropped.
@richlander, @kendrahavens - please look over the tagging.
@naamunds - The Dockerfiles are for the most part the identical to the 1.1 Dockerfiles except for the runtime and cli versions, download urls, and the debian runtime Dockerfile's FROM image.
=> Added Dockerfiles for 2.0

2.0/debian/runtime/Dockerfile
Latest CLI taken in https://github.com/dotnet/dotnet-docker-nightly/commit/cb5d064bf6476ac8f0ab7c6cb06052a725b910cf depends on a new runtime.  Tests didn't catch this.  They will be updated with another PR.  Fixing mismatched runtime image right away.
=> Update 2.0 runtime to 2.0.0-beta-001486-00

2.0/debian/sdk/Dockerfile, 2.0/nanoserver/sdk/Dockerfile, test/run-test.ps1
This version of CLI contains the new3 functionality.  Because of that the run-test script needed to be updated to invoke `dotnet new` with the appropriate parameters.  This allowed for some logic cleanup.  I also made some other minor cleanup changes.
=> Update 2.0 SDK to alpha-004847

1.0/debian/sdk/Dockerfile, 1.0/debian/sdk/hooks/post_push, 1.0/nanoserver/sdk/Dockerfile, 1.1/debian/sdk/Dockerfile, 1.1/debian/sdk/hooks/post_push, 1.1/nanoserver/sdk/Dockerfile
CLI 1.0.0 based images will continue to be produced but out of the SDK-1.0.0 branch.
=> Update 1.0.4 and 1.1.1 SDK Dockerfiles to CLI 1.0.1

update-dependencies/Config.cs, update-dependencies/Program.cs
For the cli 2.0 release there is only one moniker therefore we don't need to match on it.  Since it has been changing from time to time, this change will not require us to update the Maestro subscription as often.
cc @dagood
=> Changed update-dependencies to support matching on cli version prefix

update-dependencies/CliDependencyHelper.cs, update-dependencies/Config.cs, update-dependencies/Program.cs, update-dependencies/update-dependencies.csproj
I'm not a fan of this.  I view it as a stop-gap until the produces and consumes build tools infrastructure is in place.
=> Refactor update-dependencies to update the runtime Dockerfiles

2.0/debian/runtime/Dockerfile, 2.0/debian/sdk/Dockerfile, 2.0/nanoserver/runtime/Dockerfile, 2.0/nanoserver/sdk/Dockerfile
FYI - the `-portable` suffix is supposedly going to be dropped from the runtime tarball so another update will have to happen down the road.
=> Update 2.0 Dockerfiles to use new portable artifacts

manifest.json
This is being done so that customer can more easily switch from the official repo to nightly to test the latest bits (e.g. a service fix).  This also helps ensure consistency between the official and nightly repo which helps with releases.
=> Produce the same tags in nightly as official

build-and-test.ps1, test/run-test.ps1
- Updated CI scripts to read Docker Hub repo info from manifest.  This makes it easier to test changes when you want to build and push to a private repo.
- Disabled the NuGet package workaround for when packages aren't yet available on NuGet.org.
=> Misc CI script cleanup

build-and-test.ps1, build-pipeline/dotnet-docker-linux-images.json, build-pipeline/dotnet-docker-post-image-build.json, build-pipeline/dotnet-docker-windows-images.json, build-pipeline/pipeline.json, manifest.json, test/run-test.ps1
- Upgraded to use latest image builder tool.  This required a manifest schema change.  
- Refactored manifest to make use of tagVariables which will make patch Tuesday work easier/less error prone.
- Renamed build-pipeline build definitions to align with the dotnet-docker repo.  This makes merging changes easier.
=> Upgrade to latest image builder

2.0/runtime-deps/stretch/Dockerfile, 2.0/runtime/stretch/Dockerfile, 2.0/sdk/stretch/Dockerfile, README.md, build-and-test.ps1, manifest.json, test/run-test.ps1
1. Added new Debian Stretch based Dockerfiles for 2.0
2. Updated CI scripts to read manifest in order to determine what to build/test.  I would eventually like to remove the build script and replace it with the image-builder tool but that is currently blocked on some Windows/Docker issues.
=> Add debian:stretch based Dockerfiles for 2.0

build-pipeline/dotnet-docker-post-image-build.json
This was an oversight on https://github.com/dotnet/dotnet-docker-nightly/pull/355.  This doesn't cause a functional issue other than the multi-arch tags are getting re-pushed in the insider repo unnecessarily.
=> Add missing repo filter to publishManifest build leg

2.0/runtime/nanoserver-insider/README.md, README.md, build-and-test.ps1, build-pipeline/dotnet-docker-linux-amd64-images.json, build-pipeline/dotnet-docker-linux-arm32v7-images.json, build-pipeline/dotnet-docker-post-image-build.json, build-pipeline/dotnet-docker-windows-amd64-images.json, manifest.json, test/run-test.ps1
As part of fixing the readme, the version of the image-builder tool was updated to the latest since it now has support for generating the tags readme documentation.
=> Update broken dockerfile paths in readme

build-pipeline/dotnet-docker-linux-amd64-images.json, build-pipeline/dotnet-docker-linux-arm32v7-images.json, build-pipeline/dotnet-docker-post-image-build.json, build-pipeline/dotnet-docker-windows-amd64-images.json
This change is needed with the latest image-builder as commands are now parameters.
=> Remove '--command' arg from builds

1.0/runtime/nanoserver/Dockerfile, 1.0/sdk/nanoserver/Dockerfile, 1.1/runtime/nanoserver/Dockerfile, 1.1/sdk/nanoserver/Dockerfile, 2.0/runtime/nanoserver/amd64/Dockerfile, 2.0/sdk/nanoserver/amd64/Dockerfile, manifest.json
Updating Nano Server Dockerfiles to be based on 10.0.14393.1593
=> Updating Nano Server Dockerfiles to be based on 10.0.14393.1593

README.md
Is this enough?  Thoughts on the `Supported Linux arm32 tags` heading?  Should `Supported` be changed as well?
Related dotnet/dotnet-docker#223
=> Add note to readme stating arm is in preview

1.0/sdk/jessie/Dockerfile, 1.0/sdk/nanoserver/Dockerfile, 1.1/sdk/jessie/Dockerfile, 1.1/sdk/nanoserver/Dockerfile
CI is expected to fail until build is available.
=> Update 1.* sdk images to 1.1.3

1.0/runtime/nanoserver/Dockerfile, 1.0/sdk/nanoserver/Dockerfile, 1.1/runtime/nanoserver/Dockerfile, 1.1/sdk/nanoserver/Dockerfile, 2.0/runtime/nanoserver/amd64/Dockerfile, 2.0/sdk/nanoserver/amd64/Dockerfile, 2.1/runtime/nanoserver/amd64/Dockerfile, 2.1/sdk/nanoserver/amd64/Dockerfile, manifest.json
Updating Nano Server Dockerfiles to be based on 10.0.14393.1715
=> Updating Nano Server Dockerfiles to be based on 10.0.14393.1715

build-and-test.ps1, test/Dockerfile.linux.publish, test/Dockerfile.linux.testrunner, test/Dockerfile.test, test/Microsoft.DotNet.Docker.Tests/DockerHelper.cs, test/Microsoft.DotNet.Docker.Tests/Dockerfile.linux.publish, test/Microsoft.DotNet.Docker.Tests/Dockerfile.linux.test, test/Microsoft.DotNet.Docker.Tests/Dockerfile.test, test/Microsoft.DotNet.Docker.Tests/Dockerfile.windows.test, test/Microsoft.DotNet.Docker.Tests/DotNetImageType.cs, test/Microsoft.DotNet.Docker.Tests/ImageTests.cs, test/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj, test/run-test.ps1
The Powershell tests are just getting too complicated to maintain.  Trying xunit tests instead using C#.  This is needed as part of https://github.com/dotnet/dotnet-docker/issues/286 which requires more complicated logic to determine which sdk, runtime-deps, runtime image pairings to test together as each image will not exist for every version.
=> Refactor Powershell based tests as xunit tests

build-pipeline/pipeline.json, netci.groovy, test/run-test.ps1
This is necessary in order to stop producing the 2.1-runtime-deps images since they are identical to 2.0.  The 2.1 tests will build a 2.1 self-contained app and verify it will run on the 2.0-runtime-deps image.
Related to https://github.com/dotnet/dotnet-docker/issues/286
=> Consolidate 2.0 & 2.1 build legs on linux

build-pipeline/pipeline.json, netci.groovy
This is necessary in order to consolidate the duplicated 1.* SDK Dockerfiles.  The 1.* tests will require the common 1.* SDK image to test the various runtime and runtime-deps images therefore all 1.* images must be built in the same build leg.
Related to dotnet/dotnet-docker#294
=> Consolidate 1.* build legs

test/Microsoft.DotNet.Docker.Tests/ImageDescriptor.cs, test/Microsoft.DotNet.Docker.Tests/ImageTests.cs, test/Microsoft.DotNet.Docker.Tests/VerifyImageDescriptor.cs, test/run-test.ps1
This should make it easier to maintain the tests as new .NET Core versions are released and support is dropped for older versions.
=> Refactor all utests to use Theory and MemberData

build-pipeline/dotnet-docker-linux-arm32v7-images.json
Added logic to skip arm tests since there aren't any currently defined.  This change is needed as part of https://github.com/dotnet/dotnet-docker-nightly/pull/435 because a [Theory without data is considered invalid](https://github.com/xunit/xunit/issues/1113).  This change should be reverted with https://github.com/dotnet/dotnet-docker-nightly/pull/434.
=> Skip tests in arm build legs

README.md, manifest.json
related to https://github.com/dotnet/dotnet-docker/issues/285
=> Modified fully qualified SDK tags to 2.0 to include the CLI version

test/Dockerfile.linux.testrunner, test/Microsoft.DotNet.Docker.Tests/DockerHelper.cs, test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
This change helps verify the integrity of CI and official builds.  If the images being tested, weren't just built, something is configured incorrectly.
=> Add logic to tests to verify tested images exist

1.0/runtime/nanoserver/Dockerfile, 1.1/runtime/nanoserver/Dockerfile, 1.1/sdk/nanoserver/Dockerfile, 2.0/runtime/nanoserver/amd64/Dockerfile, 2.0/sdk/nanoserver/amd64/Dockerfile, 2.1/runtime/nanoserver/amd64/Dockerfile, 2.1/sdk/nanoserver/amd64/Dockerfile, manifest.json
Updating Nano Server Dockerfiles to be based on 10.0.14393.1770
=> Updating Nano Server Dockerfiles to be based on 10.0.14393.1770

1.0/runtime/nanoserver/Dockerfile, 1.1/runtime/nanoserver/Dockerfile, 1.1/sdk/nanoserver/Dockerfile, 2.0/runtime/nanoserver/amd64/Dockerfile, 2.0/sdk/nanoserver/amd64/Dockerfile, 2.1/runtime/nanoserver/amd64/Dockerfile
Update Nano Server Dockerfile to use the escape directive (https://docs.docker.com/engine/reference/builder/#escape).
Tested these changes by running `build-and-test.ps1 -Filter *nanoserver*`. Tested the scope of the escape directive through the following sequence -
1. Build an image using a Dockerfile that uses backtick as the escape directive. Say, image tag is `backtick:latest`
2. Prepare a Dockerfile that uses `backtick:latest`. Add some additional commands in the Dockerfile that use `\` backslash as the line continuation character.
3. Build an image using the Dockerfile created in step #2. Expectation is a Dockerfile parse error due to `\` character.
=> Add escape directive in Nano Server Dockerfiles

build-pipeline/dotnet-docker-linux-amd64-images.json, build-pipeline/dotnet-docker-linux-arm32v7-images.json, build-pipeline/dotnet-docker-post-image-build.json, build-pipeline/dotnet-docker-windows-amd64-images.json
Ensures build sources and output directory is cleaned up before starting a build.
=> Set build cleanup options

README.md, manifest.json
`ltsc2016` is the new tag that is being added everywhere to identify Windows Server 2016.  All previously produced tags are maintained to prevent breaking users who have taken a dependency on them.
=> Add Nano Server ltsc2016 tags

1.0/runtime/nanoserver/Dockerfile, 1.1/runtime/nanoserver/Dockerfile, 1.1/sdk/nanoserver/Dockerfile, 2.0/runtime/nanoserver/amd64/Dockerfile, 2.0/sdk/nanoserver/amd64/Dockerfile, 2.1/runtime/nanoserver/amd64/Dockerfile, 2.1/sdk/nanoserver/amd64/Dockerfile, build-and-test.ps1, manifest.json
Generating images with `nanoServerVersion` suffixed tag is not consistent with (https://hub.docker.com/r/microsoft/nanoserver/).  Produce only two variants - Semi Annual Channel (SAC) and 1709.
Refer https://github.com/dotnet/dotnet-docker/issues/328
=> Stop producing NanoServerVersion suffixed tags

build-pipeline/pipeline.json
Fixing build break from https://github.com/dotnet/dotnet-docker-nightly/pull/486
@dotnet-bot skip ci please.
=> Fix build break due to sac2016 folder refactor

test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
Related to dotnet/dotnet-docker#333
=> Update self-contained tests to use portable rid where possible

test/Microsoft.DotNet.Docker.Tests/DockerHelper.cs, test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
In a Nano Server 1709 container the default user i.e. _ContainerUser_ will not have access to a volume. Only the _ContainerAdministrator_ will have access. Hence these changes execute docker run command with user as _ContainerAdministrator_ in case of Nano Server 1709 unit tests.
These changes are required for enabling CI on Nano Server 1709. Related to https://github.com/dotnet/dotnet-docker-nightly/issues/468
=> Specify user as ContainerAdministrator while running Nano Server 1709 unit tests

2.0/runtime/nanoserver-1709/amd64/Dockerfile, 2.0/sdk/nanoserver-1709/amd64/Dockerfile, 2.1/runtime/nanoserver-1709/amd64/Dockerfile, 2.1/sdk/nanoserver-1709/amd64/Dockerfile
`dotnet.exe` path should be in system (as opposed to local) PATH. Setting such variable requires admin access. Since in Nano Server 1709 the default user i.e. `ContainerUser`, switch to `ContainerAdministrator` to set the system environment variable.
Related to https://github.com/dotnet/dotnet-docker/issues/344
Edit: Replaced "Fixes" as "Related To"
=> Add dotnet to system PATH

test/Microsoft.DotNet.Docker.Tests/DockerHelper.cs, test/Microsoft.DotNet.Docker.Tests/ImageDescriptor.cs, test/Microsoft.DotNet.Docker.Tests/ImageTests.cs, test/Microsoft.DotNet.Docker.Tests/OS.cs
1. The logic to cleanup Docker volumes was failing.  A change was required to correctly check if the volume existed or not.
2. I refactored how the test data is declared slightly to hopefully make it easier to maintain going forward.
=> Ensure volumes get cleaned up and test data refactor

build-pipeline/dotnet-docker-linux-arm32v7-images.json, test/Microsoft.DotNet.Docker.Tests/DockerHelper.cs, test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
Related to #399.
The deadlock was caused from calling Process.StandardOutput.ReadToEnd after Process.WaitForExit.  See https://msdn.microsoft.com/en-us/library/system.diagnostics.process.standardoutput(v=vs.110).aspx for details.
=> fix deadlock in tests and enable tests in arm builds

update-dependencies/Invoke-UpdateDependencies.ps1
This change is necessary in order to get Maestro build hook to run correctly.
=> Modify Invoke-UpdateDependencies to run container as ContainerUser
